=== ZilyaN/SEM_VEB/dtd/task4-theaters.dtd
<!ELEMENT theaters (theater+)>

<!ELEMENT theater (type,difference,subtypes)>

<!ELEMENT type (#PCDATA)>
<!ELEMENT difference (#PCDATA)>
<!ELEMENT subtypes (subtype)?>
<!ELEMENT subtype (#PCDATA)>

<!ATTLIST theater id CDATA#REQUIRED>
<!ATTLIST subtype id CDATA#REQUIRED>

=== ZilyaN/SEM_VEB/task4-theaters.xml
<?xml version="1.0" encoding= 'utf-8'?>
<!DOCTYPE theaters SYSTEM "task4-theaters.dtd">
<theaters>
    <theater id="1">
        <type>Драматический</type>
        <difference>
            В основе происходящего на сцене всегда лежит знаменитое литературное произведение
        </difference>
    </theater>
    <theater id="2">
        <type>Оперный</type>
        <difference>
            Актеры передают главную мысль посредством вокала. В основе происходящего на сцене лежит либретто
            литературное произведение, на сюжет которого композитор кладет музыку.
        </difference>
    </theater>
    <theater id="3">
        <type>Балетный</type>
        <difference>
            Передача сюжета, главной мысли посредством классического или характерного (народного) танца.
        </difference>
    </theater>
    <theater id="4">
        <type>Театр кукол</type>
        <difference>
            В этом искусстве актерами являются не сами люди, а куклы, которыми управляют.
        </difference>
        <subtypes>
            <subtype id="1">Стендовый</subtype>
            <subtype id="2">Театр живой куклы</subtype>
            <subtype id="3">Напольный</subtype>
            <subtype id="4">Наручной</subtype>
            <subtype id="5">Настольный</subtype>
        </subtypes>
    </theater>
    <theater id="5">
        <type>Театр пантомимы</type>
        <difference>
            Основным средством создания художественного образа является пластика человеческого тела, без
            использования слов.
        </difference>
    </theater>
    <theater id="6">
        <type>Театр абсурда</type>
        <difference>
            В таких пьесах отсутствует логическое построение, нет сюжета как такового, а есть только нагромождение
            фактов, диалогов, судеб разных людей и их нелепых поступков.
        </difference>
    </theater>
    <theater id="7">
        <type>Моноспектакль</type>
        <difference>
            Спектакль, в котором главный герой является единственным исполнителем и ведет монолог.
        </difference>
    </theater>
    <theater id="8">
        <type>Иммерсивный театр</type>
        <difference>
            Иммерсивный театр основывается на полном погружении зрителя в мир постановки. Единственное правило - молчать
            и не снимать маску.
        </difference>
    </theater>
    <theater id="9">
        <type>Уличный театр</type>
        <difference>
            Действие уличного тетра происходит на открытом воздухе. Главный момент в таких представлениях -
            импровизация. Такие
            представления часто подвергаются вмешательству зрителей, потому что между ними и актёрами нет чёткой
            границы.
        </difference>
    </theater>
    <theater id="10">
        <type>Театр теней</type>
        <difference>
            Для постановок в театре теней используют большой полупрозрачный экран и марионеток.
        </difference>
    </theater>
</theaters>
